[project]
authors = [{name = "Willow Ahrens", email = "ahrens@gatech.edu"}]
name = "binsparse-tests"
requires-python = ">=3.11"
version = "0.1.0"
dependencies = [
    "numpy>=2.5.2,<3",
]

[project.optional-dependencies]
hdf5 = ["h5py>=3.16.0,<4"]
zarr = ["zarr>=3.3.0,<4"]

scipy = ["scipy"]
torch = ["torch"]
sparse = ["sparse"]
conversions = ["scipy", "torch", "sparse"]

[dependency-groups]
test = [
    "pytest>=7.4.4",
    "pytest-cov>=4.1.0",
    "pytest-xdist>=3.5.0",
    "mypy>=1.15,<2",
]
pre-commit = [
    "pre-commit>=3.6.0,<5",
]
docs = [
    "mkdocs-material>=9.7.7,<10",
    "mkdocstrings[python]>=1.0.6",
    "mkdocs-autoapi>=0.4.1",
    "ruff>=0.6.0",
]
hdf5=[
    "h5py>=3.16.0,<4",
]
zarr=[
    "zarr>=3.3.0,<4",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.dependencies]
python = ">=3.11"

[tool.pixi.environments]
test-hdf5 = { features = ["test", "hdf5"], solve-group = "default" }
test-zarr = { features = ["test", "zarr"], solve-group = "default" }
test-npz = { features = ["test"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
pre-commit = { features = ["pre-commit"], no-default-feature = true }

[tool.pixi.pypi-dependencies]
binsparse-tests = { path = ".", editable = true }

[tool.pixi.feature.pre-commit.dependencies]
python = ">=3.11"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "B", "UP", "YTT", "BLE", "C4", "T10", "ISC", "ICN", "PIE", "PYI", "RSE", "RET", "SIM", "PGH", "FLY", "NPY", "PERF", "RUF022", "TID"]
ignore = ["PYI024"]

[tool.mypy]
ignore_missing_imports = true
exclude = []
files = ["binsparse_tests"]

[tool.pytest.ini_options]
addopts = [
    "--doctest-modules",
    "--doctest-ignore-import-errors",
    "--cov-report=term-missing",
    "--cov=binsparse_tests",
]
testpaths = ["binsparse_tests"]
junit_family = "xunit2"
strict_config = true
strict_markers = true

[tool.pixi.feature.test.tasks.test]
args = [
    { arg = "njobs", default = "logical" },
]
depends-on = [
    { task = "type-check", environment = "test", args = [] },
    { task = "test-only", args = ["{{ njobs }}"] },
]

[tool.pixi.feature.test.tasks.test-only]
cmd = "pytest -n {{ njobs }}"
args = [
    { arg = "njobs", default = "logical" },
]
default-environment = "test"

[tool.pixi.feature.test.tasks.type-check]
cmd = "python -m mypy"
default-environment = "test"

[tool.pixi.feature.docs.tasks.serve-docs]
cmd = "mkdocs serve --strict"
default-environment = "docs"

[tool.pixi.feature.docs.tasks.build-docs]
cmd = "mkdocs build --strict"
default-environment = "docs"
